/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      colors: {
        "primary": "var(--ui-primary)",
        "on-primary": "var(--ui-on-primary)",
        "primary-container": "var(--ui-primary-container)",
        "on-primary-container": "var(--ui-on-primary-container)",
        "secondary": "var(--ui-secondary)",
        "on-secondary": "var(--ui-on-secondary)",
        "secondary-container": "var(--ui-secondary-container)",
        "on-secondary-container": "var(--ui-on-secondary-container)",
        "tertiary": "var(--ui-tertiary)",
        "on-tertiary": "var(--ui-on-tertiary)",
        "tertiary-container": "var(--ui-tertiary-container)",
        "on-tertiary-container": "var(--ui-on-tertiary-container)",
        "error": "var(--ui-error)",
        "on-error": "var(--ui-on-error)",
        "error-container": "var(--ui-error-container)",
        "on-error-container": "var(--ui-on-error-container)",
        "background": "var(--ui-background)",
        "on-background": "var(--ui-on-background)",
        "surface": "var(--ui-surface)",
        "on-surface": "var(--ui-on-surface)",
        "surface-variant": "var(--ui-surface-variant)",
        "on-surface-variant": "var(--ui-on-surface-variant)",
        "outline": "var(--ui-outline)",
        "outline-variant": "var(--ui-outline-variant)",
        "surface-container-lowest": "var(--ui-surface-container-lowest)",
        "surface-container-low": "var(--ui-surface-container-low)",
        "surface-container": "var(--ui-surface-container)",
        "surface-container-high": "var(--ui-surface-container-high)",
        "surface-container-highest": "var(--ui-surface-container-highest)",
        "surface-bright": "var(--ui-surface-bright)",
        "surface-dim": "var(--ui-surface-dim)",
        "surface-tint": "var(--ui-surface-tint)",
        "inverse-surface": "var(--ui-inverse-surface)",
        "inverse-on-surface": "var(--ui-inverse-on-surface)",
        "inverse-primary": "var(--ui-inverse-primary)",
        "primary-fixed": "var(--ui-primary-fixed)",
        "on-primary-fixed": "var(--ui-on-primary-fixed)",
        "primary-fixed-dim": "var(--ui-primary-fixed-dim)",
        "on-primary-fixed-variant": "var(--ui-on-primary-fixed-variant)",
        "secondary-fixed": "var(--ui-secondary-fixed)",
        "on-secondary-fixed": "var(--ui-on-secondary-fixed)",
        "secondary-fixed-dim": "var(--ui-secondary-fixed-dim)",
        "on-secondary-fixed-variant": "var(--ui-on-secondary-fixed-variant)",
        "tertiary-fixed": "var(--ui-tertiary-fixed)",
        "on-tertiary-fixed": "var(--ui-on-tertiary-fixed)",
        "tertiary-fixed-dim": "var(--ui-tertiary-fixed-dim)",
        "on-tertiary-fixed-variant": "var(--ui-on-tertiary-fixed-variant)",
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "40px",
        "gutter": "12px",
        "sidebar_width": "320px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
      }
    },
  },
//  plugins: [
//    require("@tailwindcss/forms"),
//    require("@tailwindcss/container-queries"),
//  ],
}
